config/routes.rb
Rails.application.routes.draw do
  get '/users/login_form',to: 'users#login_form'
  post '/users/login',to: 'users#login'

  root 'home#index'
  
  post '/add_likes/:id',to: 'likes#add_like'
  post '/not_likes/:id',to: 'likes#not_like'
  get '/likes/index', to: 'likes#index'
  
  post '/recommend/:id',to: 'recommends#add_recommend'
  post '/no_recommend/:id',to: 'recommends#remove_recommend'
  
  
  post '/comments/:book_id',to: 'comments#create'
  get '/books/search',to: 'books#search'
  resources :users, except: :edit
  resources :books
  get '/users/:id/detail_edit',to: 'users#detail_edit'
  post '/users/:id/detail_update',to: 'users#detail_update'
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  has_many :likes,dependent: :destroy
  has_many :books,dependent: :destroy
  
  mount_uploader :img, ImgUploader
  validates :name,presence: true,length: {minimum: 2}
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email,presence: true,uniqueness: { case_sensitive: false },format: { with: VALID_EMAIL_REGEX }
  has_secure_password
  validates :password_digest, presence: true,length: {minimum: 6}
  validates :text,length: {maximum: 170}
  
  def write_count
    return Book.where(user_id: self.id).count(id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  protect_from_forgery except: :search # searchアクションを除外
  protect_from_forgery except: :login # searchアクションを除外

  before_action :new_book
  before_action :params_user_id,only: [:show,:detail_update,:detail_edit]
  before_action :books_nation,only: [:show]
  before_action :no_login_user,except: [:new,:create,:login,:login_form,:show]

  def index
    @users = User.all.order(created_at: :desc)
  end
  
  def new
    @user = User.new
  end
  
  def create
    @user = User.new(safe_user)
    
    if @user.save
      session[:user_id] = @user.id
      flash[:notice] = "ログインできました"
      redirect_to user_path(@user.id)
    else
      flash[:notice] = "ログインできませんでした"
      render 'new'
    end
    
  end

  def show
    current_user
    @likes = Like.where(user_id: @user.id).order('created_at desc').page(params[:page]).per(25)
    @comments = Comment.where(user_id: @user.id)
    @recommends = Recommend.where(user_id: @user.id)
  end
  
  def login
    user = User.find_by(email: params[:user][:email])
    if user && user.authenticate(params[:user][:password])
      flash[:notice] = "ログインできました"
      session[:user_id] = user.id
      redirect_to user_path(user.id)
    else
      flash[:notice] = "ログインできません"
      redirect_to users_login_form_path
    end
  end
  
  def login_form
    @user = User.new
    if session[:user_id]
      flash[:notice] = "ログイン済みです"
      current_user
      redirect_to user_path(@current_user.id)
    end
  end
  
  def destroy
    log_out
    redirect_to root_path
  end
  
  def book_page
    
  end
  def detail_edit
    
  end
  def detail_update
    if @user.update(user_detail)
      flash[:notice] = "更新しました"
      redirect_to user_path(@user.id)
    else
      flash[:notice] = "未入力、文字数を超えているものがあります"
      render "detail_edit"
    end
  end
  
  def safe_user
    params.require(:user).permit(:name,:email,:password)
  end
  
  def safe_edit
    params.require(:user).permit(:name,:email,:img,:remove_img)
  end
  def user_detail
    params.require(:user).permit(:text,:name,:img)
  end
  def params_user_id
    @user = User.find_by(id: params[:id])
  end
    PER = 25
  def books_nation
    @books = Book.where(user_id: @user.id).order('created_at desc').page(params[:page]).per(PER)
  end
end

app/helpers/users_helper.rb
module UsersHelper
  
  def login_user(user)
    session[:user_id] = user.id
  end
  
  def current_user
    if session[:user_id]
      @current_user ||= User.find_by(id: session[:user_id])
    end
  end
  
  def logged_in?
    !current_user.nil?
  end
  
  def log_out
    session.delete(:user_id)
    @current_user = nil
    flash[:notice] = "ログアウトしました"
  end
  
  def no_login_user
    unless logged_in?
      flash[:notice] = "ログインしてください"
      redirect_to root_path
    end
  end
  
end

app/views/users/_errors.html.erb
<% if @user.errors.any? %>
  <%= @user.errors.count %>
  <% @user.errors.full_messages.each do |msg| %>
  <li><%= msg %></li>
  <% end %>
<% end %>

app/views/users/_form.html.erb
<%= form_for :user,url: url,html: {id: "login-form",method: :post} do |f| %>
  <% page_url = request.path %>
  <% unless page_url == '/users/login_form' || page_url == '/' %>
    <div class= "form-group user-login">
      名前:<%= f.text_field :name,id: "name",class: "form-control",placeholder: "名前を入力してください" %>
    </div>
  <% end %>
  <div class = "form-group user-login">
    メールアドレス:<%= f.text_field :email,id: "email",class: "form-control",placeholder: "メールアドレスを入力してください" %>
  </div>
  <div class = "form-group user-login">
    パスワード:<%= f.password_field :password,id: "password",class: "form-control",placeholder: "パスワードを入力してください" %>
  </div>
  <%= f.submit @submit,id: "btn-login",class: "btn login-btn header-link" %>
<% end %>
 

app/views/users/_img_action.html.erb
<script type="text/javascript">
　  
  $(function() {
    
   function readURL(input) {
     if (input.files && input.files[0]) {
       var reader = new FileReader();
       reader.onload = function (e) {
         $('.img_prev').attr('src', e.target.result);
       }
       reader.readAsDataURL(input.files[0]);
     }
   }
   
   $(".book_img").change(function(){
     readURL(this);
   });
  });
</script>
　
<!--</div>-->

app/views/users/_list_function.html.erb
<script>
  (function($){

$(document).ready(function(){
  var tablist = $(".tab-head li");
  var tabbody = $(".tab-body > li");
  
  console.log(tabbody);
  tablist.click(function(){
    var idx = tablist.index($(this));
    console.log(idx);
    tablist.removeClass("on").eq(idx).addClass("on");
    tabbody.removeClass("on").eq(idx).addClass("on");
  });
});


})(jQuery);
</script>

app/views/users/detail_edit.html.erb
<h1>ユーザ編集ページです</h1>
<%= form_for :user,url: {action: :detail_update}  do |f| %>
<div class = "text">
<div class = "user-profile-box">
    <%= image_tag @user.img.url, class: :img_prev,width: 200,height: 200,class: "user-icon"%>
  <div class= "user-profile-content">
        <div class = "user-name">{{a}}</div>
      <div class = "user-text">{{b}}</div>  
    <!--ユーザ詳細を載せる-->
      <!--ユーザ詳細を載せる-->
  </div>
</div>

 <div class = "form_group detail-form">画像:
  <%= f.file_field :img, class: 'book_img' %>
 </div>
 <div class ="form_group detail-form"> 
    名前:<%= f.text_field :name,placeholder: "名前を入力してください",required: true,class: 'form-control form-user-name',html: {value: @user.name,maxlength: 10},"v-model.trim" => "a",name: "user[name]" %>
   <div class = "word-count form-group">残り文字数{{20 - a.length}}</div>
   <div class = "count_alert_name"></div>

 </div>

  <div class = "form_group detail-form">
    プロフィール:<%= f.text_area :text,rows: 5,class: 'form-control form-user-text',placeholder: "プロフィールがまだ記載されてません",html: {value: @user.text,maxlength: 170 },"v-model.trim" => "b",name: "user[text]"%>
   <div class = "word-count form-group">残り文字数{{170 - b.length}}</div>
    <div class = "count_alert"></div>
  </div>
</div>

  <%= f.submit "変更を保存",class: "btn" %>
<% end %>

<%= render partial: 'img_action' %>
<script type = "text/javascript">
   new Vue({
    el: ".text",
    data: {a: "", b: ""},
  });
$('.form-user-text').bind('keydown keyup keypress change',function(){
  var txt = $(this).val(),
  new_txt = $.trim(txt.replace(/\n/g, "")),
  couter = new_txt.length;
  if(couter > 170){
  $('.count_alert').html("170文字を超えています");
  }else{
  $('.count_alert').html("");
  }
});
$('.form-user-name').bind('keydown keyup keypress change',function(){
  var txt = $(this).val(),
  new_txt = $.trim(txt.replace(/\n/g, "")),
  couter = new_txt.length;
  if(couter > 20){
  $('.count_alert_name').html("20文字を超えています");
  }else{
  $('.count_alert_name').html("");
  }
});
</script>

app/views/users/form.html.erb
<div class="dropdown">
  <!-- 切替ボタンの設定 -->
  <button type="button" class="btn btn-secondary dropdown-toggle" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
    ドロップダウンボタン
  </button>
  <!-- ドロップメニューの設定 -->
  <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
    <a class="dropdown-item" href="#">メニュー1</a>
      <% if logged_in? %>
      　<%= link_to @current_user.name,user_path(@current_user.id),class: "dropdown-item" %>
      　<%= link_to "ログアウト",user_path(@current_user.id),method: :delete,class: "dropdown-item" %>
      　<%= link_to "おすすめ本の作成",new_book_path,class: "dropdown-item" %>
      　<%= link_to "本一覧",books_path,class: "dropdown-item" %>
    <% else %>  
      <%= link_to "ログイン",users_login_form_path,class: "dropdown-item" %>
    <% end %>
  </div><!-- /.dropdown-menu -->
</div><!-- /.dropdown -->

app/views/users/index.html.erb
<h1>ユーザ一覧です</h1>

<% @users.each_with_index do |user,i| %>
  <%= image_tag user.img.url %>
  <%= user.name %>
  
<% end %>

app/views/users/login_form.html.erb
<% @submit = "ログイン" %>

<!------ Include the above in your HEAD tag ---------->
<section id="login">
  <div class="container">
  	<div class="row">
	    <div class="col-xs-12 content-center">
  	    <div class="form-wrap">
          <h1>ログインフォームです</h1>
          <%= render partial: 'form',locals: {url: "login"} %>
          <a href="javascript:;" class="forget" data-toggle="modal" data-target=".forget-modal">Forgot your password?</a><hr>
          <%= link_to "登録がまだの方はこちらから",new_user_path %>
          <hr>
  	    </div>
  		</div> <!-- /.col-xs-12 -->
  	</div> <!-- /.row -->
  </div> <!-- /.container -->
</section>

<div class="modal fade forget-modal" tabindex="-1" role="dialog" aria-labelledby="myForgetModalLabel" aria-hidden="true">
	<div class="modal-dialog modal-sm">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal">
					<span aria-hidden="true">×</span>
					<span class="sr-only">Close</span>
				</button>
				<h4 class="modal-title">Recovery password</h4>
			</div>
			<div class="modal-body">
				<p>Type your email account</p>
				<input type="email" name="recovery-email" id="recovery-email" class="form-control" autocomplete="off">
			</div>
			<div class="modal-footer">
				<button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
				<button type="button" class="btn btn-custom">Recovery</button>
			</div>
		</div> <!-- /.modal-content -->
	</div> <!-- /.modal-dialog -->
</div> <!-- /.modal -->

app/views/users/new.html.erb
<h1>サインインフォームです</h1>
<p>ユーザ登録してない方は、登録してください</p>
<%= render partial: 'errors' %>
<% @url = "create"  %>
<% @submit = "新規登録"  %>

<%= render partial: 'form' %>

app/views/users/show.html.erb
<% provide(:title,@user.name) %>
<h1><%= @user.name %>のページです</h1>
<div class = "text">
  <div class = "user-profile-box">
    <%= image_tag @user.img.url,class: "user-icon" %>
  <div class= "user-profile-content">
    <p class = "user-name">  
      <%= @user.name %>
    </p>
    <p class = "user-text">
      <%= @user.text %>  
      <!--ユーザ詳細を載せる-->
    </p>
  </div>
  <% if @current_user%>
      <%= link_to "ユーザプロフィールを編集する","/users/#{@user.id}/detail_edit" if session[:user_id] == @current_user.id%>
  <% end %>
  </div>  
</div>


<div class = "list">
  <ul class = "tab-head">
    <li class = "on">
      紹介した本
      <%= create_book_count(@user.id) %>
    </li>
    <li>
      気になるリスト
      <%= user_like_count(@user.id) %>
    </li>
    <li>
      おすすめ本リスト
      <%= user_recommend_count(@user.id) %>
    </li>
    <li>
    　紹介した本に対するコメント
    　<%= user_return_comment(@user.id) %>
    </li>
    <li>
      コメント履歴
      <%= user_history_comment(@user.id) %>
    </li>
  </ul>
  <ul class = "tab-body">
    <li class = "on">
      <%= render partial: 'books/book_template' %>
    </li>  
    <li>
    <% if @likes %>
      <%= render partial: 'books/book_like_template'%>
    <% else %>
      お気に入りがありません
    <% end %>
    </li>
    <li>
    <% if user_recommend_count(@user.id) == 0 %>
      <h1>おすすめ本がありません</h1>
    <% elsif @recommends %>
      <%= render partial: 'books/book_recommend_template'%>
    <% end %>
    </li>
    <li>
      <% @books.each_with_index do |book,i| %>
        <% if book.comments %>
          <% book.comments.each do |comment| %>
          <div class = "comment-content">
            <div class = "comment-content-head">
              <%= link_to book_path(book.id) do %>
                <%= image_tag book.img.url,class: "book-image"%>
                <h2><%= book.title %></h2>  
              <% end %>
            </div>
            <div class = "comment-text">
              <%= comment.text %>
            </div>
            <div>
              <%= comment.created_at.strftime('%Y/%m/%d') %>
            </div>
          </div>
          <% end %>
        <% end %>
      <% end %>

    </li>
    <li>
      <% @comments.each do |comment| %>
        <div class = "comment-content">
          <div class = "comment-content-head">
            <%= link_to book_path(comment.book.id) do %>
              <%= image_tag comment.book.img.url,class: "book-image"%>
              <h2><%= comment.book.title %></h2>
            <% end %>
          </div>
          <div class = "comment-text">
            <%= comment.text %>
          </div>
          <div>
            <%= comment.created_at.strftime('%Y/%m/%d') %>
          </div>
        </div>
      <% end %>
    </li>
  </ul>  
</div>

<%= render partial: 'list_function' %>