config/routes.rb
Rails.application.routes.draw do
  get '/users/login_form',to: 'users#login_form'
  post '/users/login',to: 'users#login'

  root 'home#index'
  
  post '/add_likes/:id',to: 'likes#add_like'
  post '/not_likes/:id',to: 'likes#not_like'
  get '/likes/index', to: 'likes#index'
  
  post '/recommend/:id',to: 'recommends#add_recommend'
  post '/no_recommend/:id',to: 'recommends#remove_recommend'
  
  
  post '/comments/:book_id',to: 'comments#create'
  get '/books/search',to: 'books#search'
  resources :users, except: :edit
  resources :books
  get '/users/:id/detail_edit',to: 'users#detail_edit'
  post '/users/:id/detail_update',to: 'users#detail_update'
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  PER = 10
  before_action :new_book

  def index
    current_user
    @books = Book.page(params[:page]).per(PER)
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<% unless session[:user_id] %>
  <div class = "top-background">
    <div class = "top-wide">
      <div class = "col-sm-6">
        <div class = "top-title">Hello World！</div>
        <div id = "title">
          EEBooKとは、エンジニアリング系の本の評価をまとめたサイトです。あなたが読んだ本の評価や感想を書くことで、記録に残すことが可能ですし、その後読む方の助けになります。是非活用していってください!
        </div>
      </div>  
    <div class = "title-center col-sm-6">
      <% @submit = "ログイン" %>
      <% @url = users_login_path %>
     <%= render partial: "users/form",locals: {url: @url} %>
    </div>    
    </div>
  </div>
<% end %>
<div class = "body-width">
  <h1>本一覧です</h1>
  <div class = "col-sm-8 left-content">
    <%= render partial: "books/book_template" %>


  </div>
  <div class = "col-sm-4 sidebar">
    <div>
      <%= render partial: 'layouts/sidebar' %>
    </div>
  </div>
</div>