config/routes.rb
Rails.application.routes.draw do
  get '/users/login_form',to: 'users#login_form'
  post '/users/login',to: 'users#login'

  root 'home#index'
  
  post '/add_likes/:id',to: 'likes#add_like'
  post '/not_likes/:id',to: 'likes#not_like'
  get '/likes/index', to: 'likes#index'
  
  post '/recommend/:id',to: 'recommends#add_recommend'
  post '/no_recommend/:id',to: 'recommends#remove_recommend'
  
  
  post '/comments/:book_id',to: 'comments#create'
  get '/books/search',to: 'books#search'
  resources :users, except: :edit
  resources :books
  get '/users/:id/detail_edit',to: 'users#detail_edit'
  post '/users/:id/detail_update',to: 'users#detail_update'
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_header.html.erb
<header>
<nav class="navbar-default">
  <div class="container-fluid header-flex">
    
    <div class=" site-name">
      みんなの幸せニュース
    </div> 
    
    <div class=" header-content">
      <%= form_tag(books_search_path,method: :get) do %>
        <%= text_field_tag :search,'',placeholder: "タイトル",class: "form-control search-field" %>
        <%= text_field_tag :tag_search,'',placeholder: "幸せタグ",class: "form-control tag-search-field"%>
        <%= submit_tag '検索', :name => nil,class: "search-btn btn" %>
      <% end %>
    </div>
    <div class = "">
      <%= link_to "一覧ページ",books_path,class: "header-link" %>
    </div>
    <% if @current_user %>
      <div class = "">
        <%= link_to "幸せを投稿",new_book_path,class: "header-link" %>
      </div>
    <% end %>
    <div class="dropdown">
  <!-- 切替ボタンの設定 -->
    <button type="button" class="btn btn-secondary dropdown-toggle" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
     <% if logged_in? %>
       <%= @current_user.name %>
     <% else %>
       ログイン
     <% end %>
    </button>
  <!-- ドロップメニューの設定 -->
    <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
      <% if logged_in? %>
        　<%= link_to "ユーザ詳細",user_path(@current_user.id),class: "dropdown-item" %>
        　<%= link_to "ログアウト",user_path(@current_user.id),method: :delete,class: "dropdown-item" %>
        　<%= link_to "幸せを投稿",new_book_path,class: "dropdown-item" %>
        　<%= link_to "一覧",books_path,class: "dropdown-item" %>
        <% else %>
        <%= link_to "ログイン",users_login_form_path,class: "dropdown-item" %>
      <% end %>
      </div><!-- /.dropdown-menu -->
    </div><!-- /.dropdown -->
  </div>
</nav>
</header>

app/views/layouts/_sidebar.html.erb
<h2>いいねランキング</h2>
  <% @likes = Like.group(:book_id).order('count(user_id) desc').limit(10)  %>
  <% @likes.each do |like| %>
    <% book = like.book %>
    <%= render partial: "layouts/sidebar_template",locals: {book: book} %>
  <% end %>

app/views/layouts/_sidebar_template.html.erb
<div class = "side-bar-flex">
  <%= link_to book_path(book.id) do %>
    <div class = "side-img-style col-sm-5">
      <%= image_tag(book.img.url) %>
    </div>
    <div class = "side-bar-content col-sm-7">
      <p><%= book.title %></p>
      <div class = "user-show">
        <div class = "sidebar-user-img">
          <%= image_tag book.user.img.url,class: "user-img" %>
        </div>
        <div class = "sidebar-user-name">
          <%= book.user.name %>        
        </div>
      </div>

      <div class = "like-count">気になる!<%= book.likes_count %>件</div>
      <div class = "recommend_count">おすすめ!<%= book.recommend_counter %>件</div>
    </div>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) %></title>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link href="//netdna.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
    <script src="//netdna.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
    <script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
    <script src="https://code.jquery.com/jquery-2.2.4.min.js"></script>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src='https://cdnjs.cloudflare.com/ajax/libs/vue/1.0.10/vue.js'></script>
    <script src='https://cdnjs.cloudflare.com/ajax/libs/marked/0.3.5/marked.js'></script>
    <%= csrf_meta_tags %>
    
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

  </head>

  <body>
    <%= render partial: "layouts/header"  %>
    <% if flash[:notice] %>
      <div class = "flash-message">
        <%= flash[:notice] %>
      </div>
    <% end %>
    <% page_url = request.path %>
    <% unless page_url == '/' || page_url == '/users/login_form' || page_url == '/users/new' || page_url == '/books/new' || page_url == "/books/#{@book.id}/edit" %>
      <div class = "body-width">
        <div class = "col-sm-8 left-content">
          <%= yield %>
        </div>
        <div class = "col-sm-4 sidebar">
          <div>
            <%= render partial: 'layouts/sidebar' %>
          </div>
        </div>
      </div>
    <% else %>
    <div class = "no-sidebar">
    <%= yield %>  
    </div>
    <% end %>

<footer class="page-footer font-small blue">

  <!-- Copyright --><hr>
  <div class="footer-copyright text-center py-3">© 2018 Copyright:
    <a href="https://halogen322.com"> 運営者:佐藤 現</a>
  </div>
  <!-- Copyright -->

</footer>
  </body>
</html>